// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeamskvfywucljdvabgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lYW1za3ZmeXd1Y2xqZHZhYmdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Nzk4OTUsImV4cCI6MjA2NzU1NTg5NX0.CT7epDKudLwhR4X7jQsYiSiBblLdxnNQ8JNWE4sAJ_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});